# **Constants**

In [2]:
import tensorflow as tf

## **Tensor**

- Deeplearning framework는 기본적으로 Tensor를 다루는 도구다.

- Tensor를 다룰 때 가장 중요한 것!!
    ### -> **SHAPE** !!!
    (해보면 알겠지만, 제일 에러 많이 나는 이유, 제일 헷갈리는 것, 개발할 때 우리가 이론을 알아야 하는 이유, 함수들의 설정 값을 확인해야 하는 이유)

## **Tensor 생성**

우리가 생성하는 것은 tf.Tensor 데이터!

#### **항상 체크해야 할 것!
   - shape
   - dtype(데이터 타입이 같아야 연산이 가능하다.)

In [3]:
li = [1, 2, 3]

In [4]:
type(li)

list

### Constant (상수)
- tf.constant()
    - list -> Tensor
    - tuple -> Tensor
    - Array -> Tensor

In [5]:
li_ten = tf.constant([1, 2, 3])
li_ten

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [6]:
li_ten_f = tf.constant([1., 2., 3.])
li_ten_f

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [7]:
tu_ten = tf.constant(((1, 2, 3), (1., 2., 3.)), name="sample")
tu_ten

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [1., 2., 3.]], dtype=float32)>

In [8]:
import numpy as np

In [9]:
arr = np.array([1., 2., 3.])
arr_ten = tf.constant(arr)
arr_ten

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

### **Numpy array 추출**

In [10]:
arr_ten.numpy(), type(arr_ten.numpy())

(array([1., 2., 3.]), numpy.ndarray)

In [11]:
li_ten.numpy(), type(li_ten.numpy())

(array([1, 2, 3]), numpy.ndarray)

### **shape, dtype 항상 체크!!**

In [12]:
li_ten.shape, tu_ten.shape

(TensorShape([3]), TensorShape([2, 3]))

In [13]:
arr_ten.dtype, li_ten.dtype

(tf.float64, tf.int32)

### **데이터 타입 컨트롤하는 방법**
- tf.cast

In [14]:
tensor = tf.constant([1, 2, 3], dtype=tf.float64)
tensor

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [15]:
tf.cast(tensor, dtype=tf.int16)

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 2, 3], dtype=int16)>

#### **간단 퀴즈**
#### 아래 코드를 에러 없이 실행 하시오.

In [16]:
arr_ten, li_ten

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>)

In [17]:
arr_ten * li_ten

InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a double tensor but is a int32 tensor [Op:Mul]

In [18]:
arr_ten * tf.cast(li_ten, tf.float64)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 4., 9.])>

### **특정 값의 Tensor 생성**
- tf.ones
- tf.zeros
- tf.range

In [19]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [20]:
tf.zeros((2, 5), dtype="int32")

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

In [21]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [22]:
tf.range(1,11)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>

#### **간단 퀴즈**
n을 입력하면 첫항이 1이고 공비가 2인 등비수열을 생성하는 함수를 만드시오.

In [23]:
def geometric_sequence(n):
    r = tf.range(n, dtype = tf.int32)
    s = tf.ones(n, dtype=tf.int32) * 2
    return s**r

In [24]:
print(geometric_sequence(10))

tf.Tensor([  1   2   4   8  16  32  64 128 256 512], shape=(10,), dtype=int32)


#### Random Value(난수)
- 무작위 값을 생성할 때 필요.
- Noise를 재현 한다거나, test를 한다거나 할 때 많이 사용됨
- 데이터 타입은 상수형태로 반환됨

tf.ramdom에 구현되어 있음.
- tf.random,normal
    - Gaussian Normal Distribution
- tf.random.uniform
    - Uniform Distrubution
    
    
    이보다 더 많다.

In [25]:
shape = (3, 3)

In [26]:
tf.random.normal(shape)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.8224277 ,  1.1661077 ,  0.16622333],
       [-1.0426589 , -1.6640888 ,  0.63514453],
       [ 0.92954195, -0.37368968, -0.43083578]], dtype=float32)>

In [27]:
tf.random.uniform(shape)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.09347415, 0.37047803, 0.47771847],
       [0.8057269 , 0.58445776, 0.2892877 ],
       [0.72148144, 0.83781695, 0.0256362 ]], dtype=float32)>

- Random seed 관리하기!!
    - Random value로 보통 가중치를 초기화
    - 이외에도 학습과정에서 Random value가 많이 사용됨
    - 이를 관리 안 해주면, 자신이 했던 작업이 동일하게 복구 혹은 재현이 안됨!!
- tf.random.set_seed({seed_number})
=> 항상 Random seed를 고정해두고 개발한다!!
(주의 할 점은 해당 개발물에 사용되는 난수가 모두 TensorFlow에서 생성된 것이 아닐 수 있다는 것이다.)

In [28]:
seed =7777

In [29]:
tf.random.set_seed(seed)
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep="\n")

tf.Tensor([0.959749], shape=(1,), dtype=float32)
tf.Tensor([0.8677443], shape=(1,), dtype=float32)


In [30]:
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep="\n")

tf.Tensor([0.22878075], shape=(1,), dtype=float32)
tf.Tensor([0.87772965], shape=(1,), dtype=float32)


In [31]:
tf.random.set_seed(seed)
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep="\n")

tf.Tensor([0.959749], shape=(1,), dtype=float32)
tf.Tensor([0.8677443], shape=(1,), dtype=float32)
