# Tensor 연산

In [1]:
import tensorflow as tf
import numpy as np

아래의 기본 연산은 특수 메서드를 이용하여 연산자 오버로딩이 되어 있으므로 그냥 연산자 기호를 사용하는게 가능!

- tf.add:덧셈
- tf.subtract:뺄셈
- tf.multiply:곱셈
- tf.divide:나눗셈
- tf.pow:n-제곱
- tf.negative:음수 부호

In [2]:
a = tf.range(6, dtype=tf.int32)
b = 2 * tf.ones(6, dtype=tf.int32)

tf.add(a, b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7])>

In [3]:
a *b

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 0,  2,  4,  6,  8, 10])>

#### 여러가지 연산
- tf.abs:절대값
- tf.sign:부호 
- tf.round:반올림
- tf.ceil:올림
- tf.floor:내림
- tf.square:제곱
- tf.sqrt:제곱근
- tf.maximum:두 텐서의 각 원소에서 최댓값만 반환
- tf.minimum:두 텐서의 각 원소에서 최솟값만 반환
- tf.cumsum:누적합
- tf.cumprod:누적곱

In [4]:
tf.maximum(a, b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5])>

In [5]:
tf.sqrt(tf.cast(a, tf.float32))

<tf.Tensor: shape=(6,), dtype=float32, numpy=
array([0.        , 0.99999994, 1.4142134 , 1.7320508 , 2.        ,
       2.236068  ], dtype=float32)>

#### Axis 이해하기

In [6]:
rank_2 = tf.random.normal((3, 3))

In [7]:
rank_2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.29574266, -0.7126614 , -0.22266713],
       [-0.3059238 , -0.45612356,  0.26534867],
       [ 0.13767688,  0.16740176, -1.3329597 ]], dtype=float32)>

In [8]:
rank_2[1]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.3059238 , -0.45612356,  0.26534867], dtype=float32)>

In [9]:
rank_2[1, 2]

<tf.Tensor: shape=(), dtype=float32, numpy=0.26534867>

In [10]:
rank_3 = tf.random.normal((3, 3, 3))

In [11]:
rank_3

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-0.93071723,  0.21833657,  0.64150983],
        [-1.0415325 , -0.6437539 ,  0.2905047 ],
        [ 1.7244744 , -0.93482834, -0.61292756]],

       [[ 0.18391486,  0.19544968,  0.3439882 ],
        [ 0.4303004 ,  0.47238088,  1.0199566 ],
        [-1.3477253 , -0.39391845,  1.1390836 ]],

       [[-2.2071261 ,  0.73052406, -0.29324847],
        [ 0.3846113 ,  1.1826668 , -1.4700603 ],
        [-0.505264  , -2.200393  ,  1.5337538 ]]], dtype=float32)>

In [12]:
rank_3[1, 1, 2]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0199566>

#### 차원 축소 연산
- tf.reduce_mean:설정한 축의 평균을 구한다.
- tf.reduce_max:설정한 축의 최댓값을 구한다.
- tf.reduce_min:설정한 축의 최솟값을 구한다.
- tf.reduce_prod:설정한 축의 요소를 모두 곱한 값을 구한다.
- tf.reduce_sum:설정한 축의 요소를 모두 더한 값을 구한다.

In [13]:
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5])>

In [14]:
tf.reduce_sum(a, axis=0)

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [15]:
tf.reduce_sum(a, axis=0, keepdims=True)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([15])>

#### 행렬과 관련된 연산
- tf.matmul:내적
- tf.linalg.inv:역행렬

In [16]:
a = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
b = tf.constant([[1, 1], [1, 1]], dtype=tf.float32)
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [1., 1.]], dtype=float32)>

In [17]:
a = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5, 0. ],
       [0. , 1. ]], dtype=float32)>

#### 크기 및 차원을 바꾸는 행렬
이를 사용 할 때는 축을 잘 이해하고 사용해야한다.
- tf.reshape:벡터 행렬의 크기 변환
- tf.transpose:전치 연산
- tf.expand_dims:지정한 축으로 차원을 추가 
- tf.squeeze:벡터로 차원을 축소

In [21]:
a = tf.range(6, dtype=tf.int32)   # [0, 1, 2, 3, 4, 5]
print("a     :", a, "\n")
a_2d = tf.reshape(a, (2, 3))    #1차원 벡터는 2x3 크기의 2차원 행렬로 변환   
print("a_2d  :", a_2d, "\n")
a_2d_t = tf.transpose(a_2d)#2x3 크기의 2차원 행렬을 3x2 크기의 2차원 행렬로 변환
print("a_2d_t:", a_2d_t, "\n")
a_3d = tf.expand_dims(a_2d, 0)#2x3 크기의 2차원 행렬을 1x2x3 크기의 3차원 행렬로 변환
print("a_3d  :", a_3d, "\n")
a_4d = tf.expand_dims(a_3d, 3)#1x2x3 크기의 3차원 행렬을 1x2x3x1 크기의 4차원 행렬로 변환
print("a_4d  :", a_4d, "\n")
a_ld = tf.squeeze(a_4d)
print("a_ld   :", a_ld, "\n")#1x2x3x1 크기의 4차원 행렬을 1차원 벡터로 변환

a     : tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32) 

a_2d  : tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32) 

a_2d_t: tf.Tensor(
[[0 3]
 [1 4]
 [2 5]], shape=(3, 2), dtype=int32) 

a_3d  : tf.Tensor(
[[[0 1 2]
  [3 4 5]]], shape=(1, 2, 3), dtype=int32) 

a_4d  : tf.Tensor(
[[[[0]
   [1]
   [2]]

  [[3]
   [4]
   [5]]]], shape=(1, 2, 3, 1), dtype=int32) 

a_ld   : tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32) 



#### 텐서를 나누거나 두 개 이상의 텐서를 합치는 명령
- tf.slice:특정 부분을 추출
- tf.split:분할
- tf.concat:합치기
- tf.tile:복제-붙이기
- tf.stack:합성
- tf.unstack:분리

In [22]:
a = tf.reshape(tf.range(12), (3, 4))
a

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [23]:
tf.slice(a, [0, 1], [2, 3]) #(0, 1)위치에서 (2개, 3개)만큼 뽑아낸다.

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]])>

In [24]:
a1, a2 = tf.split(a, num_or_size_splits=2, axis=1) #가로축을 따라 2개로 분리
print(a1)
print(a2)

tf.Tensor(
[[0 1]
 [4 5]
 [8 9]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  3]
 [ 6  7]
 [10 11]], shape=(3, 2), dtype=int32)


In [25]:
tf.concat([a1, a2],1) #가로축을 따라 a1,a2 합치기

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [26]:
tf.tile(a1,[1, 3]) #가로축을 따라 3개로 복사-붙이기

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[0, 1, 0, 1, 0, 1],
       [4, 5, 4, 5, 4, 5],
       [8, 9, 8, 9, 8, 9]])>

In [27]:
a3 = tf.stack([a1, a2]) # 3x2 행렬 a1, a2 를 추가적인 차원으로 붙여서 2x3x2 고차원 텐서 생성
a3

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]])>

In [28]:
tf.unstack(a3, axis=1) # 2x3x2 고차원 텐서를 0차원으로 풀어서 3개의 2x2 행렬 생성

[<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[0, 1],
        [2, 3]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[4, 5],
        [6, 7]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 8,  9],
        [10, 11]])>]

---------------------------

In [29]:
a = tf.constant(((1, 2, 3), (1, 2, 3)))
b = tf.constant([1, 2, 3])

tf.matmul(a, b)

InvalidArgumentError: In[0] and In[1] has different ndims: [2,3] vs. [3] [Op:MatMul]

In [30]:
tf.matmul(a, tf.expand_dims(b, axis=1))

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[14],
       [14]])>